CREATE TABLE USUARIOS (
    NOMBRE VARCHAR(50) PRIMARY KEY,
    CONTRASEGNA VARCHAR(50) NOT NULL,
    RUTAIMGPERFIL VARCHAR(50),
    ESADMIN BOOLEAN
);


CREATE TABLE CATEGORIAS (
    NOMBRE VARCHAR(20) PRIMARY KEY
);

CREATE TABLE RESTAURANTES (
    IDREST SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    CONTRASEGNA VARCHAR(50) NOT NULL,
    RUTAIMGPERFIL VARCHAR(50),
    RUTAIMGFONDO VARCHAR(50),
    DIRECCION VARCHAR(50) NOT NULL,
    TELEFONO VARCHAR(20) NOT NULL,
    HORARIO VARCHAR(50) NOT NULL,
    CATEGORIA VARCHAR(20) NOT NULL,
    FOREIGN KEY (CATEGORIA) REFERENCES CATEGORIAS(NOMBRE)
);

CREATE TABLE PLATOS (
    IDPLATO SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(50) NOT NULL,
    RUTAIMGPLATO VARCHAR(50), 
    RESTAURANTE INTEGER NOT NULL,
    PRECIO INTEGER NOT NULL, 
    FOREIGN KEY (RESTAURANTE) REFERENCES RESTAURANTES(IDREST)
);

CREATE TABLE POSTS (
    IDCOM SERIAL PRIMARY KEY,
    CONTENIDO VARCHAR(400) NOT NULL,
    RUTAIMAGEN VARCHAR(50),
    FECHA TIMESTAMPTZ NOT NULL,
    CATEGORIA VARCHAR(20) NOT NULL,
    IDAUTOR VARCHAR(50) NOT NULL,
    FOREIGN KEY (CATEGORIA) REFERENCES CATEGORIAS(NOMBRE),
    FOREIGN KEY (IDAUTOR) REFERENCES USUARIOS(NOMBRE),
);

CREATE TABLE REVIEWS (
    IDCOM SERIAL PRIMARY KEY,
    CONTENIDO VARCHAR(400) NOT NULL,
    RUTAIMAGEN VARCHAR(50),
    FECHA TIMESTAMPTZ NOT NULL,
    IDAUTOR VARCHAR(50) NOT NULL,
    IDREST INTEGER,
    IDPLATO INTEGER,
    FOREIGN KEY (IDAUTOR) REFERENCES USUARIOS(NOMBRE),
    FOREIGN KEY (IDREST) REFERENCES RESTAURANTES(IDREST),
    FOREIGN KEY (IDPLATO) REFERENCES PLATOS(IDPLATO),
    CHECK (IDREST IS NOT NULL OR IDPLATO IS NOT NULL)
);

CREATE TABLE RESPUESTAS (
    IDCOM SERIAL PRIMARY KEY,
    CONTENIDO VARCHAR(400) NOT NULL,
    RUTAIMAGEN VARCHAR(50),
    FECHA TIMESTAMPTZ NOT NULL,
    IDAUTOR VARCHAR(50) NOT NULL,
    IDREVIEW INTEGER,
    IDPOST INTEGER,
    FOREIGN KEY (IDAUTOR) REFERENCES USUARIOS(NOMBRE),
    FOREIGN KEY (IDREVIEW) REFERENCES REVIEWS(IDCOM),
    FOREIGN KEY (IDPOST) REFERENCES POSTS(IDCOM),
    CHECK (
          (IDREVIEW IS NOT NULL AND IDPOST IS NULL) OR 
          (IDREVIEW IS NULL ANDIDPOST IS NOT NULL)
     )
);

CREATE TABLE VALORA (
    IDRESTAURANTE INTEGER NOT NULL,
    IDUSUARIO VARCHAR(50) NOT NULL,
    VALORACION INTEGER NOT NULL CHECK (VALORACION >= 0 AND VALORACION <= 5),
    PRIMARY KEY (IDRESTAURANTE, IDPERSONA),
    FOREIGN KEY (IDRESTAURANTE) REFERENCES RESTAURANTES(IDREST),
    FOREIGN KEY (IDUSUARIO) REFERENCES USUARIOS(NOMBRE)
);

CREATE TABLE REACCIONA (
    IDREACCION SERIAL PRIMARY KEY,
    IDPOST INTEGER,
    IDREVIEW INTEGER,
    IDRESPUESTA INTEGER,
    IDAUTOR INTEGER NOT NULL,
    REACCION BOOLEAN NOT NULL, -- false = dislike, 1 = like
    FOREIGN KEY (IDPOST) REFERENCES POSTS(IDCOM),
    FOREIGN KEY (IDREVIEW) REFERENCES REVIEWS(IDCOM),
    FOREIGN KEY (IDRESPUESTA) REFERENCES RESPUESTAS(IDCOM),
    FOREIGN KEY (IDAUTOR) REFERENCES USUARIOS(NOMBRE),
    -- CHECK that only one of the three post / review or response is not null
    CHECK (
        (IDPOST IS NOT NULL AND IDREVIEW IS NULL AND IDRESPUESTA IS NULL) OR
        (IDPOST IS NULL AND IDREVIEW IS NOT NULL AND IDRESPUESTA IS NULL) OR
        (IDPOST IS NULL AND IDREVIEW IS NULL AND IDRESPUESTA IS NOT NULL)
    )
);

CREATE TABLE GESTIONA (
      USUARIO VARCHAR(50) NOT NULL,
      RESTAURANTE INTEGER NOT NULL,
      FOREIGN KEY (USUARIO) REFERENCES USUARIOS(NOMBRE),
      FOREIGN KEY (RESTAURANTE) REFERENCES RESTAURANTES(IDREST)
);

-- -- DROP ALL TABLES:
-- -- DROP TABLE GESTIONA;
-- -- DROP TABLE REACCIONA;
-- -- DROP TABLE VALORA;
-- -- DROP TABLE RESPUESTAS;
-- -- DROP TABLE REVIEWS;
-- -- DROP TABLE POSTS;
-- -- DROP TABLE PLATOS;
-- -- DROP TABLE RESTAURANTES;
-- -- DROP TABLE CATEGORIAS;
-- -- DROP TABLE USUARIOS;
